version: "3.8"

services:
  app:
    build: .
    image: app
    container_name: app
    command: ["python", "app.py"]
    ports:
      - 8000:8000
    volumes:
      - ./:/app
    environment:
      commas_api_key: ${commas_api_key}
      commas_secret: ${commas_secret}
      host: ${host}
      port: ${port}
      database: ${database}
      db_username: ${db_username}
      db_password: ${db_password}
